# Generated by Django 5.1.3 on 2025-03-03 13:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='HistoryElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('title', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('text', models.TextField(blank=True, default=None, max_length=65535, null=True)),
                ('title_list', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('text_list', models.TextField(blank=True, default=None, max_length=65535, null=True)),
                ('title_img', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('id_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.historyblock')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/about/history')),
                ('id_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='about.historyelement')),
            ],
        ),
    ]
