# Generated by Django 5.1.3 on 2025-03-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyblock',
            name='id',
        ),
        migrations.RemoveField(
            model_name='historyelement',
            name='id',
        ),
        migrations.AddField(
            model_name='historyblock',
            name='id_block',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historyelement',
            name='id_element',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
