# Generated by Django 5.1.3 on 2025-03-05 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_structureblock_structureelement_structureimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structureelement',
            name='id_block',
        ),
        migrations.RemoveField(
            model_name='structureimage',
            name='id_element',
        ),
        migrations.RemoveField(
            model_name='structurelist',
            name='id_element',
        ),
        migrations.DeleteModel(
            name='StructureBlock',
        ),
        migrations.DeleteModel(
            name='StructureImage',
        ),
        migrations.DeleteModel(
            name='StructureElement',
        ),
        migrations.DeleteModel(
            name='StructureList',
        ),
    ]
