# Generated by Django 5.1.3 on 2025-03-05 08:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_remove_structureelement_id_block_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureBlock',
            fields=[
                ('id_block', models.AutoField(primary_key=True, serialize=False)),
                ('priority', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('type_block', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='StructureElement',
            fields=[
                ('id_element', models.AutoField(primary_key=True, serialize=False)),
                ('priority', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('title_h', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('title_l', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('text', models.TextField(blank=True, default=None, max_length=65535, null=True)),
                ('list_title', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('quote', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('quote_author', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('contact_post', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('contact_name', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('contact_phone', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('contact_email', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('img_title', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('id_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.structureblock')),
            ],
        ),
        migrations.CreateModel(
            name='StructureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/structure/history')),
                ('id_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.structureelement')),
            ],
        ),
        migrations.CreateModel(
            name='StructureList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_element', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('id_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.structureelement')),
            ],
        ),
    ]
