# Generated by Django 5.1.3 on 2025-03-10 07:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_structureblock_structureelement_structureimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnershipBlock',
            fields=[
                ('id_block', models.AutoField(primary_key=True, serialize=False)),
                ('priority', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='PartnershipElement',
            fields=[
                ('id_element', models.AutoField(primary_key=True, serialize=False)),
                ('priority', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('title', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('text', models.TextField(blank=True, default=None, max_length=65535, null=True)),
                ('img_title', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('id_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.partnershipblock')),
            ],
        ),
        migrations.CreateModel(
            name='PartnershipAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_paragraph', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('id_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.partnershipelement')),
            ],
        ),
        migrations.CreateModel(
            name='PartnershipImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/structure/partnership')),
                ('id_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.partnershipelement')),
            ],
        ),
        migrations.CreateModel(
            name='PartnershipList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_element', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('id_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.partnershipelement')),
            ],
        ),
    ]
