# Generated by Django 5.1.3 on 2025-03-10 11:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_partnershipblock_partnershipelement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileBlock',
            fields=[
                ('id_block', models.AutoField(primary_key=True, serialize=False)),
                ('priority', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('file', models.FileField(upload_to='files/structure/official')),
                ('id_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.fileblock')),
            ],
        ),
    ]
