# Generated by Django 5.1.3 on 2025-03-10 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_fileblock_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='FileElement',
        ),
    ]
