# Generated by Django 5.1.3 on 2025-03-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_rename_file_fileelement'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiblioMassMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_new', models.CharField(default=None, max_length=500)),
                ('image_new', models.ImageField(upload_to='images/about/media')),
            ],
        ),
        migrations.AlterField(
            model_name='fileelement',
            name='file',
            field=models.FileField(upload_to='files/about/official'),
        ),
    ]
