# Generated by Django 5.1.3 on 2025-03-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_bibliomassmedia_alter_fileelement_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnershipimage',
            name='image',
            field=models.ImageField(upload_to='images/about/partnership'),
        ),
    ]
