# Generated by Django 5.1.3 on 2025-03-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_alter_partnershipimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structureimage',
            name='image',
            field=models.ImageField(upload_to='images/about/structure'),
        ),
    ]
