# Generated by Django 5.1.3 on 2025-03-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_alter_structureimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliomassmedia',
            name='href_new',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='bibliomassmedia',
            name='image_new',
            field=models.ImageField(blank=True, null=True, upload_to='images/about/media'),
        ),
        migrations.AlterField(
            model_name='bibliomassmedia',
            name='name_new',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
