# Generated by Django 5.1.3 on 2025-03-12 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0012_bibliomassmedia_href_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliomassmedia',
            name='priority',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
