# Generated by Django 5.1.2 on 2024-11-01 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='News',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='test',
            new_name='title',
        ),
    ]
