# Generated by Django 5.1.2 on 2024-11-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_test_news_rename_test_news_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='article_text',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
