# Generated by Django 5.1.3 on 2024-11-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
