# Generated by Django 5.1.3 on 2024-11-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date_new',
            field=models.DateField(auto_now=True),
        ),
    ]
