# Generated by Django 5.1.3 on 2024-11-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_new',
            field=models.DateTimeField(null=True),
        ),
    ]
