# Generated by Django 5.1.3 on 2024-12-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_news_date_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_news_on_page', models.PositiveSmallIntegerField(verbose_name='Кол-во новостей на странице')),
            ],
        ),
    ]
