# Generated by Django 5.1.3 on 2024-12-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('count_news_on_page', models.PositiveSmallIntegerField(verbose_name='Кол-во новостей на странице')),
            ],
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
