# Generated by Django 5.1.3 on 2024-12-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_setting_delete_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='count_news_on_page',
            field=models.PositiveSmallIntegerField(verbose_name='Variable value'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Name variable'),
        ),
    ]
