# Generated by Django 5.1.3 on 2025-01-27 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_news_article_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='RightMenuLinks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Link name')),
                ('description', models.TextField(default=None, max_length=1000, null=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('priority', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
    ]
