# Generated by Django 5.1.3 on 2025-01-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rightmenulinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rightmenulinks',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
    ]
