# Generated by Django 5.1.3 on 2025-01-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_rightmenulinks_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rightmenulinks',
            name='href',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
