# Generated by Django 5.1.3 on 2025-01-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_news_article_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image_position',
            field=models.CharField(choices=[('L', 'Left'), ('R', 'Right')], default='L', max_length=1),
        ),
    ]
