# Generated by Django 5.1.3 on 2025-01-29 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_news_image_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='count_news_on_page',
            new_name='value',
        ),
    ]
