# Generated by Django 5.1.3 on 2025-02-03 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_rename_count_news_on_page_setting_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
