# Generated by Django 5.1.3 on 2025-02-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_delete_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rightmenulinks',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Link name'),
        ),
    ]
