# Generated by Django 5.1.3 on 2025-02-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_rightmenulinks_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rightmenulinks',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
