# Generated by Django 5.1.3 on 2025-02-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_rightmenulinks_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rightmenulinks',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Link name'),
        ),
    ]
