# Generated by Django 5.1.3 on 2025-02-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('article_text', models.TextField(default=None, max_length=2500, null=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('image_position', models.CharField(choices=[('L', 'Left'), ('R', 'Right')], default='L', max_length=1)),
                ('date_new', models.DateTimeField(null=True)),
            ],
        ),
    ]
