# Generated by Django 5.1.3 on 2025-03-13 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=200)),
                ('top_title', models.CharField(max_length=200)),
                ('main_text', models.TextField(max_length=4000)),
                ('list_tile', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MainPageServiceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=200)),
                ('main_page_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readers.mainpageservice')),
            ],
        ),
    ]
