# Generated by Django 5.1.3 on 2025-03-13 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainpageservice',
            old_name='list_tile',
            new_name='list_title',
        ),
    ]
