# Generated by Django 5.1.3 on 2025-03-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0002_rename_list_tile_mainpageservice_list_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpageservicelist',
            name='service_href',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
