# Generated by Django 5.1.3 on 2025-03-31 12:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0004_alter_mainpageservicelist_service_href'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('title', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('text', models.TextField(blank=True, default=None, max_length=65535, null=True)),
                ('list_title', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('contact_title', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('contact_phone', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('contact_form', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('contact_email', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('main_page_service_list_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readers.mainpageservicelist')),
            ],
        ),
    ]
