# Generated by Django 5.1.3 on 2025-03-31 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0005_serviceelement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_element', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('id_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readers.serviceelement')),
            ],
        ),
    ]
