# Generated by Django 5.1.3 on 2025-04-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0006_servicelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceelement',
            name='contact_form_href',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
    ]
