# Generated by Django 5.1.3 on 2025-04-29 11:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0008_ruleblock_ruletitle_ruleelement_ruleelementlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilitiesBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('title_block', models.CharField(blank=True, default=None, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacilitiesElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('title_element', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('href', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('id_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readers.facilitiesblock')),
            ],
        ),
        migrations.CreateModel(
            name='FacilitiesTextList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('id_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readers.facilitieselement')),
            ],
        ),
    ]
